# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bd48eec7dea7810b976a5ede5ca91dbbd83273755d26245c90c621f99b9cd2ebe7af0b8972b21b9eb8593e21f63c6e68fe95a51ee7ebfca0a1df1e080c83c8e0

test:
  secret_key_base: 84a2f645476adbc1f12294fe6b3b62ee93482b35a74e5d3b9df7d70b197a9e22c96436e5570b580a551a4f9f0fc57a8d6a66644234791e0a7a172e96d4aa5c79

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
